package:
  name: varify
  version: "3.0.0"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: |
    # Check if pre-bundled assets exist (critical for HTML generation)
    if [ ! -f dist/report.html ]; then
      echo "ERROR: dist/report.html not found!"
      echo "Please run 'npm run build:report' before building the conda package"
      exit 1
    fi
    # Copy dist into src/varify for package inclusion
    cp -r dist src/varify/dist
    {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python>=3.10,<3.13
    - pip
    - setuptools
  run:
    - python>=3.10,<3.13
    - conda-forge::numpy>=2.2.0
    - pandas>=2.2.0
    - bioconda::pysam>=0.23.0
    - bioconda::vcfpy>=0.13.8
    - python-dateutil>=2.9.0
    - pytz>=2025.0
    - six>=1.17.0
    - tzdata>=2025a
    - setuptools>=80.0.0

test:
  commands:
    - varify --help

about:
  home: https://github.com/Lupphes/Varify
  license: GPL-3.0-or-later
  summary: "Variant File Report Generator"
  description: |
    Varify is a tool for generating reports from variant files. It is designed to be used with VCF files, 
    but can be used with any tabular variant file format. Varify is designed to be used with the output of variant calling pipelines, 
    and can be used to generate reports for quality control, variant filtering, and variant annotation.

extra:
  channels:
    - bioconda
    - conda-forge
    - defaults
