package:
  name: varify
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python=3.12
  run:
    - python=3.12
    - pandas=2.2.3
    - conda-forge::plotly=6.0.1
    - bioconda::pysam
    - bioconda::vcfpy
    - conda-forge::dominate

test:
  commands:
    - varify --help

about:
  home: https://github.com/Lupphes/Varify
  license: GPL-3.0-or-later
  summary: "A tool for genome processing"

extra:
  channels:
    - bioconda
    - conda-forge
    - defaults
