package:
  name: varify
  version: "0.2.1"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python>=3.10,<3.13
    - pip
    - setuptools
  run:
    - python>=3.10,<3.13
    - pandas=2.2.3
    - setuptools
    - bioconda::pysam=0.23.0
    - bioconda::vcfpy=0.13.8
    - conda-forge::jinja2=3.1.6
    - conda-forge::matplotlib=3.10.1
    - conda-forge::seaborn=0.13.2
    - conda-forge::numpy=2.2.4
    - conda-forge::plotly=6.0.1
    - conda-forge::python-kaleido=0.2.1
    - bioconda::igv-reports=1.14.1
    
test:
  commands:
    - varify --help

about:
  home: https://github.com/Lupphes/Varify
  license: GPL-3.0-or-later
  summary: "Variant File Report Generator"
  description: |
    Varify is a tool for generating reports from variant files. It is designed to be used with VCF files, 
    but can be used with any tabular variant file format. Varify is designed to be used with the output of variant calling pipelines, 
    and can be used to generate reports for quality control, variant filtering, and variant annotation.

extra:
  channels:
    - bioconda
    - conda-forge
    - defaults
